### ISSUE TITLE
Am I doing correctly?

### ISSUE THREAD

**Issue by dmsalsgh97** [cailab-tamu/scTenifoldKnk#1]
Hi, first, your virtual KO seems a very interesting idea!

I'm curious about how the scTenifoldKnk works, so I tried it with the test data provided in the package.

scRNAseq <- system.file("single-cell/example.csv",package="scTenifoldKnk")
scRNAseq <- read.csv(scRNAseq, row.names = 1)

I expected it will generate a heatmap like below,

![image](https://user-images.githubusercontent.com/42495757/112715190-55701180-8f22-11eb-80e2-a4856197948c.png)

but, I get those for WT and KO(knockout g100)
![wt](https://user-images.githubusercontent.com/42495757/112715230-8a7c6400-8f22-11eb-9d27-cd8921f9106b.png)
![ko](https://user-images.githubusercontent.com/42495757/112715222-881a0a00-8f22-11eb-89fa-f924e2900a43.png)

Am I doing correctly?

**Comment by dosorio** [comment]
Hi @dmsalsgh97,

Yes, however, due to the size of the demo dataset some parameters need to be adjusted. Please refer to line 67 at https://github.com/cailab-tamu/scTenifoldKnk/blob/master/inst/benchmark/benchmarkDataProcessing.R

Let me know if you have any other questions.

Best wishes,

Daniel
