### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Eomesodermin** [cailab-tamu/scTenifoldKnk#11]
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo cailab-tamu/scTenifoldKnk@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/cailab-tamu/scTenifoldKnk/tarball/HEAD' failed
  
 I know this is a generic error but i get this error across two different OS. Unsure how to proceed. Any ideas?

**Comment by dosorio** [comment]
Hi @Eomesodermin, Thanks for letting me know. scTenifoldKnk is available through the CRAN repositories at https://cran.r-project.org/web/packages/scTenifoldKnk/index.html. You can install it using install.packages('scTenifoldKnk')

Best,

Daniel

**Comment by Eomesodermin** [comment]
Thank you :)
