### ISSUE TITLE
Questions about running scTenifoldKnk

### ISSUE THREAD

**Issue by abedkurdi** [cailab-tamu/scTenifoldKnk#16]
Hello there,
I would like to ask a few questions about scTenifoldKnk: is it mandatory to run the tool on an entire sample? Is it possible to run it on a specific cluster in a single-cell sample after clustering and annotation? What do you recommend to use: normalized or not normalized counts?

Thank you in advance.

**Comment by dosorio** [comment]
Hi @abedkurdi,

Thanks for using scTenifoldKnk. The input depends on the question you may want to solve. For example, if you are interested in knowing the function of a gene in a tissue, you can use the entire dataset, but if you are interested in cell-type specific roles, you may use a single cluster instead. 

If you normalize the data before input, please use a normalization that produces only positive values and deactivate the quality control step with ```QC=FALSE```

Please let me know if you have any other questions,

Best wishes,

Daniel

**Comment by abedkurdi** [comment]
Thanks a lot!
