### ISSUE TITLE
The result changes every time, is it normal??

### ISSUE THREAD

**Issue by gdk43** [cailab-tamu/scTenifoldKnk#2]
Hi,
First of all, thank you for developing a good package.

I have one question during the package operation
After virtual perturbation with scTenifoldKnk
Is it normal to change every time when looking at genes perturbed with 
unique(c(gKO, X$diffRegulation$gene[X$diffRegulation$p.adj <0.05]))??

The first result is like this 
"Hnf4a"         "Cyp7b1"        "Mep1b"         "Napsa"         "Slc7a13"       "Slc22a19"      "Akr1c14"       "Cyp2a4"        "Cd36"          "Slc5a8"        "Acsm3"         "Slc22a7"       "Lpl"      
"Mep1a"         "Kap"           "Tmigd1"        "Slc6a18"       "Atp11a"        "Slc22a13"      "Cyp2d9"        "Acy3"          "Nudt19"        "Mpv17l"        "Rnf24"         "Slc27a2"       "Slc5a10"      
"Gstm1"         "Bdh1"          "Ces2c"         "Cndp2"         "Ggt1"          "BC035947"      "Slco1a1"       "Agps"          "Ly6a"          "Mogat1"        "Ace"           "Cyp4a10"       "Slco3a1"      
"Aadat"         "Ehhadh"        "Ugt3a1"        "Chpt1"         "Cyp4b1"        "Cyp2e1"        "B4galt5"       "Bhmt2"         "Slc22a6"       "Slc22a2"       "Gclc"          "Slc22a12"      "Myo5a"        

The second result is like this 
"Hnf4a"    "Cyp7b1"   "Mep1b"    "Slc22a19" "Akr1c14"  "Slc22a7"  "Cyp2a4"   "Napsa"    "Slc7a13"  "Slc22a13" "Rnf24"    "Cd36"     "Acsm3"    "Cyp2d9"   "Tmigd1"   "Slc5a8"   "Mep1a"    "Lpl"      "Bdh1"    
"Kap"      "Slc6a18"  "Gstm1"    "Mpv17l"   "Cyp4a10"  "Atp11a"   "BC035947" "Ace"      "Agps"     "Ces2c"    "Mme"      "Myo5a"    "Slc27a2"  "Slco1a1"  "Nudt19"   "Acy3"     "Ghr"      "Aadat"    "Slc5a10" 
"Ugt3a1"   "Ggt1"     "Pou3f3"   "Slco3a1"  "Mogat1"   "Gclc"     "Ehhadh"   "Cdo1"     "Chpt1"    "Hsd11b1"  "Reep5"    "Dmgdh"    "B4galt5" 

and the third also came out differently...

thank you!

**Comment by dosorio** [comment]
Hi @gdk43,

Yes, it is normal. The network construction step is based on the resampling of the original count matrix. The procedure is described in https://www.sciencedirect.com/science/article/pii/S2666389920301872. If you want to get a stable result add a seed value in your script, and it will do the job.

Let me know if you have any other questions. 

Best wishes,

Daniel

**Comment by gdk43** [comment]
Hi dosorio~.

Thank you for your answer :)

GD
