### ISSUE TITLE
gko

### ISSUE THREAD

**Issue by Leonrunning** [cailab-tamu/scTenifoldKnk#3]
Hi team of scTenifoldKnk,

Thanks for providing this solution of virtual gene knockout. 

While I am following the scTenifoldKnk.R, I have issues to run the knockout function due to no object of "gKO" . I am not sure how to create this object. Does it mean the gene we want to knockout out?

Sorry, I am new to this area and any help is highly appreciated.

thanks

Leon

**Comment by dosorio** [comment]
Hi @Leonrunning ,

Thank you very much for using scTenifoldKnk. Could you please provide more detail of what function are you using and the data you are using as input?

Best wishes,

Daniel

**Comment by Leonrunning** [comment]
> Hi @Leonrunning ,
> 
> Thank you very much for using scTenifoldKnk. Could you please provide more detail of what function are you using and the data you are using as input?
> 
> Best wishes,
> 
> Daniel


Hi Daniel,

Thanks for your reply. The issue is solved when the work is conducted within the same R environment you provided.

thanks

Leon

**Comment by dosorio** [comment]
Great! Thank you for letting me know.

Best wishes,

Daniel
