### ISSUE TITLE
is it possible to speed up the scTenifoldKnk

### ISSUE THREAD

**Issue by Leonrunning** [cailab-tamu/scTenifoldKnk#4]
Hi the scTenifoldKnk Team,

Thanks for developing this package. While I have tested the functions of scTenifoldKnk using the example dataset, I have issues to play with my own data matrix. 

It is pretty slow for a matrix with about 20,000 genes. I can not make it to work with 2000 cells and it still takes about 16 hours for a matrix with less than 100 cells.

Do you have any suggestions to speed it up? By the way, I am working in R.

thanks

Leon

**Comment by dosorio** [comment]
Hi Leon,

Thanks for using scTenifoldKnk! My recommendation is to remove those genes expressed in less than 5% of the cells. Examples of the required running time are available at https://github.com/cailab-tamu/scTenifoldNet#running-time

Please let me know if you have any other questions,

Best wishes,

Daniel

**Comment by Leonrunning** [comment]
> Hi Leon,
> 
> Thanks for using scTenifoldKnk! My recommendation is to remove those genes expressed in less than 5% of the cells. Examples of the required running time are available at https://github.com/cailab-tamu/scTenifoldNet#running-time
> 
> Please let me know if you have any other questions,
> 
> Best wishes,
> 
> Daniel

Hi Daniel,

If there is no better solution, I would do as you suggested. Thanks for your reply.

thanks
Leon
