### ISSUE TITLE
Error in `[.data.frame`(countMatrix, , selectedCells) :    undefined columns selected

### ISSUE THREAD

**Issue by marvelouscandy** [cailab-tamu/scTenifoldKnk#8]
Hi,

I was trying to run scTenifoldKnk on a single cell RNA seq dataset that we generated in our lab. But when I read in the file, it keeps giving me the following error:
Error in `[.data.frame`(countMatrix, , selectedCells) : 
  undefined columns selected

This is the code that I used to import the dataset.

scRNAseq_Kuang <- read.csv("Kuang1.csv", row.names = 1)
Kuang <- na.omit(scRNAseq_Kuang)
scTenifoldKnk(countMatrix = Kuang, gKO = 'XXX', qc_minLSize = 0)

I also included the screenshot of the format of the dataset

<img width="661" alt="Screen Shot 2021-11-16 at 7 52 13 PM" src="https://user-images.githubusercontent.com/48931695/142089747-ce251089-4325-448b-aa51-d1b68ba6ff23.png">

Any help would be appreciated if you can help me identify what had gone wrong?
Thank you very much in advance.

Best regards
Candice

**Comment by dosorio** [comment]
Hi Candice,

Thanks for using scTenifoldKnk. Could you please try using your input as a matrix? You can do it as follows:

scTenifoldKnk(countMatrix = as.matrix(Kuang), gKO = 'XXX', qc_minLSize = 0)

Please let me know if it works,

Best wishes,

Daniel

**Comment by marvelouscandy** [comment]
> Hi Candice,
> 
> Thanks for using scTenifoldKnk. Could you please try using your input as a matrix? You can do it as follows:
> 
> scTenifoldKnk(countMatrix = as.matrix(Kuang), gKO = 'XXX', qc_minLSize = 0)
> 
> Please let me know if it works,
> 
> Best wishes,
> 
> Daniel

Hi Daniel,

Thank you for your reply! I actually figured that I need to convert it into matrix. But after that I encounter another problem:

Error in countMatrix[, selectedCells] : subscript out of bounds
In addition: Warning messages:
1: In if (class(X) == "Seurat") { :
  the condition has length > 1 and only the first element will be used
2: In if (class(X) == "Seurat") { :
  the condition has length > 1 and only the first element will be used

Thank you so much for developing this tool!!! And thank you for your help!
Best regards
Candice

**Comment by marvelouscandy** [comment]
Hi Daniel,

I went back to the scQC codes, I think there is something wrong there but I don't know where. But I ran the scQC codes line by line (skipping the else condition) At the end I was able to get a matrix that passed the QC. I went ahead and checked the main code and see that you can bypass qc by saying FALSE, that is what I did.
It seems to me that the program is running now with a progress bar.

I will update if I get results. 
Best regards
Candice

**Comment by dosorio** [comment]
Thanks Candice! I will check it out.
